# -*- Makefile -*-

OBJS := $(SYSOBJS) $(MAKOOBJS) $(WINOBJS)

DEPS := $(OBJS:%.o=%.d)

SDL_CFLAGS := $(shell sdl2-config --cflags)
SDL_LFLAGS := -lSDL2_ttf $(shell sdl2-config --libs)

CXXFLAGS = -Isrc -Isrc/sys -D_SYSTEM3 -D_DEBUG_CONSOLE -MMD $(SDL_CFLAGS) -g

LIBS = -lwinmm

system3.exe: $(OBJS)
	$(CXX) $(OBJS) $(SDL_LFLAGS) $(LIBS) -o $@

src/res3/Script1.o: src/res3/Script1.rc
	windres $< $@

clean:
	rm -f $(OBJS) system3.exe $(DEPS)
