# -*- Makefile -*-

OBJS := $(SYSOBJS) $(MAKOOBJS) $(LINUXOBJS)

DEPS := $(OBJS:%.o=%.d)

SDL_CFLAGS := $(shell sdl2-config --cflags)
SDL_LFLAGS := -lSDL2_ttf $(shell sdl2-config --libs)

CXXFLAGS = -Isrc -Isrc/sys -D_SYSTEM3 -D_DEBUG_CONSOLE -MMD $(SDL_CFLAGS) -g

LIBS =

system3: $(OBJS)
	$(CXX) $(OBJS) $(SDL_LFLAGS) $(LIBS) -o $@

clean:
	rm -f $(OBJS) system3 $(DEPS)
