name: Linux Build
on: [push, pull_request]

jobs:
  build:
    if: github.ref != 'refs/heads/sdl3'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-type: ["Debug", "Release"]

    name: Linux ${{ matrix.build-type }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install Deps
      run: |
        sudo apt update
        sudo apt install libsdl2-dev libsdl2-ttf-dev libsdl2-mixer-dev librtmidi-dev nlohmann-json3-dev

    - name: Build
      run: |
        mkdir -p out/${{ matrix.build-type }}
        cd out/${{ matrix.build-type }}
        cmake -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} ../../
        make -j4
