name: Linux Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-type: ["Debug", "Release"]

    name: Linux ${{ matrix.build-type }}
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: true

    - name: Install Deps
      run: |
        sudo apt update
        sudo apt install libsdl2-dev libsdl2-ttf-dev librtmidi-dev nlohmann-json3-dev ninja-build

    - name: Build
      run: |
        cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}
        cmake --build build

    - name: Test
      run: ctest --output-on-failure --test-dir build
